# 使用する画像2つを両方とも指定します
preload = /home/marin/wallpapers/wallhaven-49d5qk_1920x1080.png
preload = /home/marin/wallpapers/wallhaven-3qrol9_1920x1080.png

# その上で、各モニターに割り当てます
wallpaper = DVI-1,/home/marin/wallpapers/wallhaven-49d5qk_1920x1080.png
wallpaper = HDMI-A-1,/home/marin/wallpapers/wallhaven-3qrol9_1920x1080.png
wallpaper = DP-1,/home/marin/wallpapers/wallhaven-3qrol9_1920x1080.png
